### ISSUE TITLE
cppUtil::DemangledName cppUtil::demangle does not work in some case

### ISSUE THREAD

**Issue by nix7965** [unsw-corg/SVF#19]
For example, if its argument is "_Z8printtttPj". (Original name "printttt(unsigned int*)")
"cppUtil::DemangledName cppUtil::demangle " cannot demangle it.

**Comment by rockysui** [comment]
Hi Kim,

What do you mean "cannot demangle it"?

Note that we only demangle some C++ functions, including constructor, destructor and virtual calls for analysis purpose.  For all other functions, we may not need demangling.

If possible, could you please send us a small concrete test case to show your issue?

**Comment by nix7965** [comment]
I referred to "_Z8printtttPj -> printttt(unsigned int*)" as this site did "https://demangler.com/"
But,  you intend your demangle function to support only C++ functions. It may be fine. 

But, I think it would be convenient if SVF suppports C function demangling.

**Comment by dtzWill** [comment]
What's the issue here (what are you trying to do that's not working)?

If you're using `cppUtil::demangle` in your program, you should probably just use `__cxa_demangle` directly or perhaps the LLVM version in `llvm/Demangle/Demangle.h`.

Perhaps a feature request where function names are demangled in graphs or something?

Oh, issue has been closed.  Carry on :).

**Comment by rockysui** [comment]
As mentioned by Will, you can simply use `__cxa_demangle ` to demangle your name. It works at my side for your `_Z8printtttPj `. However, in our analysis, we don't demangle a print function as it is side-effect free (unless you have your own purpose), and does not contribute anything to our analysis.
